#define DEFINE_EMPTY_ATTRIBUTES
#include <math.h>
#include "nvim/garray.h"
#include "nvim/memory.h"
#include "nvim/path.h"
#include "nvim/strings.h"
#include "nvim/log.h"
#include "nvim/math.h"
#include "nvim/base64.h"
#include "nvim/sha256.h"
#include "nvim/shada.h"
#include "nvim/mbyte.h"
#include "nvim/main.h"
#include "nvim/event/loop.h"
#include <lua.h>
#include <lauxlib.h>
